name:
  - battleship-rl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - numpy
  - polars
  - websockets
  - pytorch
  - pip:
    - tensorflow-macos
    - tensorflow-metal