name:
  - battleship-rl
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - numpy
  - polars
  - websockets
  - matplotlib
  - altair
  - pytorch
  - torchvision
  - torchaudio
  - vegafusion
  - vl-convert-python
  - pip:
    - tensorflow-macos
    - tensorflow-metal
    - graphifyy